site_name: 'phenix documentation'
site_description: 'A place for phenix users to call home.'
site_author: 'activeshadow and dnkcom'

repo_name: 'sandialabs/sceptre-phenix'
repo_url: 'https://github.com/sandialabs/sceptre-phenix'
edit_uri: 'https://github.com/sandialabs/sceptre-phenix-docs/edit/main/src'

docs_dir: src
site_dir: docs

theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: true
  favicon: images/favicon.ico
  logo: images/phenix.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: 'deep orange'
      accent: 'brown'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: 'deep orange'
      accent: 'brown'
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  custom_dir: 'theme'
  include_sidebar: true

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/sandialabs/sceptre-phenix-docs'
    - icon: 'fontawesome/solid/gear'
      link: '/swagger.html'
  version:
    provider: mike

extra_css:
  - stylesheets/style.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
